services:
  db:
    image: mariadb:11.6.2-noble
    restart: on-failure
    ports:
      - '3306:3306'
    env_file:
      - .env
  nginx:
    image: nginx:1.27.3-alpine
    restart: on-failure
    volumes:
      - './api/public:/usr/src/api/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - '127.0.0.1:80:80'
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './api:/usr/src/api'
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    user: 1000:1000
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./docker/mailpit/data:/data
    ports:
      - 8025:8025
      - 1025:1025
    env_file:
      - .env